### ISSUE TITLE
[$500 Bounty] Switch from fastboot to EDL/QDL

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/flash#7]
[QDL](https://en.wikipedia.org/wiki/Qualcomm_EDL_mode) should be a strict improvement
* unbrickable
* easier to get into than the [fastboot dance](https://youtu.be/gNnRmEyVSVQ?t=88)
* 2 -> 1 cables required
* save 3s off the boot time of the device waiting for fastboot USB enumeration

Seems like there's two options here:
1. flash the whole thing with firehose
2. load an EDL loader with fastboot and use the existing stuff to flash

Here's a good Python implementation: https://github.com/bkerler/edl.

**Comment by adeebshihadeh** [comment]
Bounty details:

Write a nice QDL.js library and integrate it into commaai/flash. The library only needs the functionality necessary for the flasher.
No comma hardware necessary; just show it works reliably on an Android phone and we'll do any final testing needed on our hardware.

Bounty locked once a PR is open that connects to a device in QDL and paid out once it's merged.

**Comment by aseok** [comment]
@adeebshihadeh I have started working on this. will you accept payment in crypto?

**Comment by adeebshihadeh** [comment]
I’d have to check, but I think so.

**Comment by incognitojam** [comment]
either TypeScript or JSDoc to add type hints is good!

**Comment by adeebshihadeh** [comment]
What code migration? I would pay more for a PR that I can just click merge on right now, but I haven't seen anything yet.

**Comment by adeebshihadeh** [comment]
@bongbui321 you've done a great job with a bunch of bounties. any interest in this one?

**Comment by bongbui321** [comment]
@adeebshihadeh definitely, I did see your post on discord the other day, but I have neither the comma nor an android device to start working on this bounty.

**Comment by andiradulescu** [comment]
@adeebshihadeh I can also try this, but not immediately.

@bongbui321 no comma hardware needed (https://github.com/commaai/flash/issues/7#issuecomment-1693963821), you just need an android device with QDL/qualcomm - maybe you can borrow an old one from someone else.

I will write a new comment before I start trying to lock it.

**Comment by andiradulescu** [comment]
@bongbui321 you try and lock this. I will not try in parallel. if you realize that you can't do it, I will try after.

**Comment by andiradulescu** [comment]
@adeebshihadeh noticed your changes https://github.com/commaai/agnos-builder/pull/198 - will you also update https://github.com/commaai/agnos ? this might help, since the same "methods" from "edl" and flash files will be used in/with "QDL.js".

**Comment by adeebshihadeh** [comment]
> @adeebshihadeh noticed your changes [commaai/agnos-builder#198](https://github.com/commaai/agnos-builder/pull/198) - will you also update https://github.com/commaai/agnos ? this might help, since the same "methods" from "edl" and flash files will be used in/with the new "QDL.js".

I put up a bounty for it https://github.com/commaai/agnos-builder/issues/200

**Comment by adeebshihadeh** [comment]
Done, thanks to @bongbui321!

**Comment by whutlichao** [comment]
## Bounty Application

Hello maintainers — I would like to take this issue.

**GitHub account:** `whutlichao`  
**Relevant stack:** Python, device flashing workflows, low-level tooling, systems integration

### Why I am a good fit
I am comfortable working on tooling that sits close to hardware and deployment workflows, where reliability and recovery paths matter as much as feature completeness. For a change like this, I would focus on a pragmatic implementation that improves flashing robustness without making the workflow harder to maintain.

### My understanding of this issue
My understanding is that the goal is to replace or reduce dependence on fastboot by moving to an EDL/QDL-based flashing path, since it should be more reliable, easier to enter, require fewer cables, and avoid the extra fastboot USB enumeration delay. The two viable approaches called out in the issue are a full firehose-based flashing flow or a hybrid path that loads an EDL loader via fastboot and then reuses the current flashing logic.

### Proposed execution plan
1. Review the current flashing flow and identify the cleanest migration path from fastboot to EDL/QDL
2. Evaluate both approaches described in the issue and choose the one that gives the best reliability/maintenance tradeoff
3. Use the referenced Python implementation and related documentation as a technical baseline
4. Implement the new flashing path with clear error handling, device-state checks, and recovery considerations
5. Validate the workflow end-to-end and document the final flashing behavior clearly in the PR

### Delivery expectations
- **Start:** immediately
- **Estimated turnaround:** 3-5 days for an initial PR, depending on testing constraints and review feedback
- **Deliverables:** implementation, validation notes, and any required documentation updates

If selected, I will keep the implementation practical, communicate clearly during review, and make the final behavior easy to verify.
